sudo: required
dist: xenial

language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-xenial
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt58base
  - sudo apt-get install -qq ffmpeg libavcodec-dev libavcodec-extra libavfilter-dev libavfilter-extra libavformat-dev libavutil-dev libswscale-dev

before_script:
  - export PATH=$PATH:/opt/qt58/bin

script:
  - /opt/qt58/bin/qmake
  - make
